version: '3'
services:
  docker-app:
    image: emmanuelneri/spring-boot-docker-app
    ports:
    - "8080:8080"
    depends_on:
    - docker-postgres
  docker-postgres:
    image: postgres:10.4
    environment:
    - POSTGRES_DB=docker
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker